Explicitely trying to find python3 first then fallback to python2. python command may not exists

diff --git a/dmake/dmake b/dmake/dmake
--- a/dmake/dmake
+++ b/dmake/dmake
@@ -1,4 +1,25 @@
-#!/usr/bin/env python
+#!/bin/sh
+
+# Shell commands follow
+# Next line is bilingual: it starts a comment in Python, and is a no-op in shell
+""":"
+
+# Find a suitable python interpreter
+for cmd in python3 python2 ; do
+   command -v > /dev/null $cmd && exec $cmd $0 "$@"
+done
+
+echo "OMG Python not found, exiting!" >2
+
+exit 2
+
+":"""
+# Previous line is bilingual: it ends a comment in Python, and is a no-op in shell
+# Shell commands end here
+# Python script follows (example commands shown)
+
+
+
 # PYTHON_ARGCOMPLETE_OK
 
 import sys
