Collect tests results even in case of test error (or timeout)
Tricky case: when tests failed, some tests may have not been executed,
so tests results files may be missing.
We still want to collect them if possible, without raising extra error
if we cant.
We still want to fail when the collection failed when the tests
succeeded though.

Current solution: duplicate the tests results collections commands,
wrap tests, and individual collections, with try/catch/rethrow and
help messages.

On bash, use https://stackoverflow.com/a/25180186/15151442 for
try/catch.

Maybe a better way to handle that would be to have a "super cmd" that
takes the individual test results collections cmds, and handle the
error handling and duplication in generate_command_bash|pipeline()?

Also:
- always store container id in txt files, even if tests failed
- always late-collect cobertura reports.
We reach that point either via normal flow where we do want an error
if no file found, or via test error where we don't want an error if no
file found.
Luckily, inline part of cobertura will already have failed if file is
missing; with proper error handling: we can ignore all that here.

To test things, uncomment `#- lets_fail_here` in testweb/dmake.yml

diff --git a/dmake/utils/dmake_run_docker_test b/dmake/utils/dmake_run_docker_test
--- a/dmake/utils/dmake_run_docker_test
+++ b/dmake/utils/dmake_run_docker_test
@@ -27,7 +27,12 @@ shift 2
 
 TMP_DIR=$(dmake_make_tmp_dir "${SERVICE_NAME/\//-}")
 
+set +e
 dmake_run_docker "" "${NAME}" --cidfile ${TMP_DIR}/cid.txt "$@"
+# always store container id in txt files, even if tests failed
+ret=$?
+set -e
+
 CONTAINER_ID=$(cat ${TMP_DIR}/cid.txt)
 
 if [ ! -z "${SERVICE_NAME}" ]; then
@@ -35,3 +40,5 @@ if [ ! -z "${SERVICE_NAME}" ]; then
 fi
 
 echo ${CONTAINER_ID} >> ${DMAKE_TMP_DIR}/containers_to_remove.txt
+
+exit $ret
